baseURL = '/'
languageCode = 'en-us'
title = 'Mario Mang blog'
theme = "terminal"
paginate = 10
disableLiveReload = false
disableRSS = false
disableSitemap = false
publishdir = "docs"



[params]
  contentTypeName = "posts"
  themeColor = "blue" 
  showMenuItems = 5
  showLanguageSelector = true
  fullWidthTheme = true
  centerTheme = true
  autoCover = true
  showLastUpdated = true
  favicon = "images/avatar.jpg"
  updatedDatePrefix = "Updated"
  oneHeadingSize = true
  readingTime = true
  Toc = true
  TocTitle = "catalog"

[languages]
  [languages.en]
    languageName = "English"
    title = "MarioMang Blog"
    subtitle = "record my life"
    owner = "MarioMang"
    keywords = "blog"
    copyright = "github.com/mariomang"
    menuMore = "Show more"
    readMore = "Read more"
    readOtherPosts = "Read other posts"
    newerPosts = "Newer posts"
    olderPosts = "Older posts"
    missingContentMessage = "Page not found..."
    missingBackButtonLabel = "Back to home page"
    minuteReadingTIme = "min read"
    words = "words"

    [languages.en.params.logo]
      logoText = "MarioMang"
      logoHomeLink = "/"
    [languages.en.menu]
      [[languages.en.menu.main]]
        identifire = "home"
        name = "Home"
        url = "/"
      [[languages.en.menu.main]]
        identifire = "about"
        name = "About"
        url = "/about"
      [[languages.en.menu.main]]
        identifire = "showcase"
        name = "Showcase"
        url = "/showcase"
[module]
  #replacements = "github.com/panr/hugo-theme-terminal -> themes/terminal"
[[module.imports]]
  #path = "github.com/panr/hugo-theme-terminal"

