baseURL = '/'
languageCode = 'en-us'
title = 'Mario Mang blog'
theme = "terminal"
paginate = 15
disableLiveReload = false
disableRSS = false
disableSitemap = false
publishdir = "docs"

[markup]
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = true
    hl_lines = ''
    hl_inline = false
    lineAnchors = ''
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = false
    noClasses = false
    noHl = false
    style = 'monokai'
    tabWidth = 4

[params]
  contentTypeName = "posts"
  themeColor = "blue"
  showMenuItems = 5
  showLanguageSelector = true
  fullWidthTheme = true
  centerTheme = false
  autoCover = true
  showLastUpdated = true
  favicon = "images/favicon.png"
  updatedDatePrefix = "Updated"
  oneHeadingSize = false
  readingTime = true
  Toc = true
  TocTitle = "Catalog"

[languages]
  [languages.en]
    languageName = "English"
    title = "MarioMang Blog"
    subtitle = "record my life"
    owner = "MarioMang"
    keywords = "blog"
    copyright = "github.com/mariomang"
    menuMore = "Show more"
    readMore = "Read more"
    readOtherPosts = "Read other posts"
    newerPosts = "Newer posts"
    olderPosts = "Older posts"
    missingContentMessage = "Page not found..."
    missingBackButtonLabel = "Back to home page"
    minuteReadingTIme = "min read"
    words = "words"

    [languages.en.params.logo]
      logoText = "MarioMang"
      logoHomeLink = "/"
    [languages.en.menu]
      [[languages.en.menu.main]]
        identifire = "home"
        name = "Home"
        url = "/"
      [[languages.en.menu.main]]
        identifire = "about"
        name = "About"
        url = "/about"
[module]
  #replacements = "github.com/panr/hugo-theme-terminal -> themes/terminal"
[[module.imports]]
  #path = "github.com/panr/hugo-theme-terminal"

